core/urls.py
from django.urls import path
from .views import HomeRedirectView

app_name = "core"
urlpatterns = [
    path("",HomeRedirectView.as_view(),name="home"),
]

projects/urls.py
from django.urls import path

from .views import (

    ProjectUpdateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectListView,
)

app_name = "projects"
urlpatterns = [

    path("", ProjectListView.as_view(), name="list_projects"),
    path("new/", ProjectCreateView.as_view(), name="create_project"),
    path("update/<int:pk>/", ProjectUpdateView.as_view(), name="update_project"),
    path("delete/<int:pk>/", ProjectDeleteView.as_view(), name="delete_project"),
    path("details/<int:pk>/", ProjectDetailView.as_view(), name="project_details"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("",include("core.urls")),
    path("projects/", include("projects.urls")),
    path("admin/", admin.site.urls),
]

projects/models.py
from django.db import models
from django.urls import reverse

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    client = models.CharField(max_length=100)
    responsible = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=10, decimal_places=2)
    spent = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("projects:project_details",kwargs={"pk":self.pk})

core/views.py
from django.views.generic import RedirectView





class HomeRedirectView(RedirectView):
    pattern_name = "projects:list_projects"

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView,CreateView,UpdateView,DetailView,DeleteView
from .models import Project
from django.urls import reverse_lazy

def list_projects(request):
    return render(
        request,
        "projects/project_list.html",
        {"projects": Project.objects.all(), "page_title": "Lista de Projetos"},
    )

class ProjectListView(ListView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Lista de Projetos"
        return context

    def get_context_object_name(self, object_list):
        return "projects"



class ProjectCreateView(CreateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("projects:list_projects")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Criar Projeto"
        return context

class ProjectUpdateView(UpdateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("projects:list_projects")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Editar Projeto"
        return context


def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        project.delete()
        return redirect("projects:list_projects")
    return render(
        request,
        "projects/project_confirm_delete.html",
        {"page_title": "Deletar Projeto", "project": project},
    )


def project_details(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(
        request,
        "projects/project_detail.html",
        {"page_title": "Detalhes do Projeto", "project": project},
    )


class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy("projects:list_projects")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Deletar Projeto"
        return context

class ProjectDetailView(DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Detalhes do Projeto"
        return context

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  {% block styles %}{% endblock styles %}

  <title>TW Projects - {{ page_title }}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'projects:list_projects' %}">TW Projects</a>
    </div>
  </nav>

  <main class="container">
    {% block content %}{% endblock content %}
  </main>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

projects/templates/projects/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ page_title }}</h1>

  <p>Tem certeza que deseja deletar o projeto <strong>{{ project.title }}</strong>?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Deletar</button>
    <a class="btn btn-primary" href="{% url 'projects:list_projects' %}" class="btn btn-default">Cancelar</a>
  </form>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ page_title }}</h1>

  <p><strong>Título:</strong> {{ project.title }}</p>
  <p><strong>Descrição:</strong> {{ project.description }}</p>
  <p><strong>Data de início:</strong> {{ project.start_date }}</p>
  <p><strong>Data de término:</strong> {{ project.end_date }}</p>
  <p><strong>Cliente:</strong> {{ project.client }}</p>
  <p><strong>Responsável:</strong> {{ project.responsible }}</p>
  <p><strong>Orçamento:</strong> R$ {{ project.budget }}</p>
  <p><strong>Gastos:</strong> R$ {{ project.spent }}</p>

  <a href="{% url 'projects:update_project' pk=project.pk %}" class="btn btn-primary">Editar</a>
  <a href="{% url 'projects:delete_project' pk=project.pk %}" class="btn btn-danger">Deletar</a>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block styles %}
  <style>
    #id_description {
      height: 100px;
    }
  </style>
{% endblock styles %}

{% block content %}
  <h1>{{ page_title }}</h1>

  <form method="POST">
    {% csrf_token %}

    <div class="mb-3">
      <label for="{{ form.title.id_for_label }}" class="form-label">Título</label>
      {{ form.title|add_class:"form-control" }}
    </div>

    <div class="mb-3 form-floating">
      {{ form.description|add_class:"form-control"|remove_attr:"rows"|remove_attr:"cols"|attr:"placeholder:Descrição" }}
      <label for="{{ form.description.id_for_label }}">Descrição</label>
    </div>

    <div class="row mb-3">
      <div class="col">
        <label for="{{ form.start_date.id_for_label }}" class="form-label">Data de início</label>
        {{ form.start_date|add_class:"form-control" }}
      </div>
      <div class="col">
        <label for="{{ form.end_date.id_for_label }}" class="form-label">Data de término</label>
        {{ form.end_date|add_class:"form-control" }}
      </div>
    </div>

    <div class="row mb-3">
      <div class="col">
        <label for="{{ form.client.id_for_label }}">Cliente</label>
        {{ form.client|add_class:"form-control" }}
      </div>
      <div class="col">
        <label for="{{ form.responsible.id_for_label }}">Responsável</label>
        {{ form.responsible|add_class:"form-control" }}
      </div>
    </div>

    <div class="row mb-3">
      <div class="col">
        <label for="{{ form.budget.id_for_label }}">Orçamento</label>
        {{ form.budget|add_class:"form-control" }}
      </div>
      <div class="col">
        <label for="{{ form.spent.id_for_label }}">Gastos</label>
        {{ form.spent|add_class:"form-control" }}
      </div>
    </div>

    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="{% url 'projects:list_projects' %}" class="btn btn-danger">Cancelar</a>
  </form>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ page_title }}</h1>

  {% if projects %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Título</th>
          <th scope="col">Data Início</th>
          <th scope="col">Data Fim</th>
          <th scope="col">Cliente</th>
          <th scope="col">Responsável</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for project in projects %}
          <tr>
            <td>{{ project.title }}</td>
            <td>{{ project.start_date }}</td>
            <td>{{ project.end_date }}</td>
            <td>{{ project.client }}</td>
            <td>{{ project.responsible }}</td>
            <td>
              <a 
                href="{% url 'projects:project_details' pk=project.pk %}" 
                class="btn btn-success"
              >
                Detalhes
              </a>
              <a
                href="{% url 'projects:update_project' pk=project.pk %}" 
                class="btn btn-primary"
              >
                Editar
              </a>
              <a 
                href="{% url 'projects:delete_project' pk=project.pk %}" 
                class="btn btn-danger"
              >
                Excluir
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Nenhum projeto cadastrado.</p>
  {% endif %}
  <a href="{% url 'projects:create_project' %}" class="btn btn-primary">Novo Projeto</a>
{% endblock %}